# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BOOKLORE_VERSION=latest
ARG BASE_VERSION=15

FROM --platform=linux/amd64 ghcr.io/booklore-app/booklore:${BOOKLORE_VERSION} AS upstream

FROM ghcr.io/daemonless/nginx-base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG BOOKLORE_VERSION
ARG PACKAGES="openjdk21-jre"
ARG UPSTREAM_URL="https://api.github.com/repos/booklore-app/booklore/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:6060/api/health"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="BookLore" \
      org.opencontainers.image.description="Self-hosted digital library with smart shelves, metadata, OPDS support, and built-in reader." \
      org.opencontainers.image.source="https://github.com/daemonless/booklore" \
      org.opencontainers.image.url="https://booklore.org/" \
      org.opencontainers.image.documentation="https://booklore-app.github.io/booklore-docs/" \
      org.opencontainers.image.licenses="AGPL-3.0" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Media Management" \
      io.daemonless.volumes="/app/data,/books,/bookdrop" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}"

# Install Java runtime
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Copy application from upstream
COPY --from=upstream /app/app.jar /app/app.jar
COPY --from=upstream /usr/share/nginx/html /var/www/html

# Create directories (use /app/data to match upstream for migration compatibility)
RUN mkdir -p /app/data /books /bookdrop /app/logs && \
    chown -R bsd:bsd /app/data /books /bookdrop /app /var/www/html

# Copy service definitions and configs
COPY root/ /

# Make scripts executable
RUN chmod +x /etc/services.d/*/run /etc/cont-init.d/* /healthz 2>/dev/null || true

# Write version (passed from build script via --build-arg)
ARG APP_VERSION=latest
RUN echo "${APP_VERSION}" > /app/version

ENV BOOKLORE_PORT=6060 \
    SPRING_DATASOURCE_URL="" \
    SPRING_DATASOURCE_USERNAME="" \
    SPRING_DATASOURCE_PASSWORD="" \
    JAVA_OPTS=""

# --- Expose (Injected by Generator) ---

# --- Volumes (Injected by Generator) ---
VOLUME /app/data /books /bookdrop